/** Private workbench; all permissions and transitions are enforced again server-side. */
export function organicPage(csrf:string,nonce:string):string {
  if(!/^[A-Za-z0-9._-]+$/.test(csrf)||!/^[A-Za-z0-9_-]+$/.test(nonce)) throw new Error('INVALID_PAGE_TOKEN');
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aurora Nexus | Evolução orgânica</title>
<style nonce="${nonce}">:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#071b24;color:#edf5f5;font:16px system-ui,sans-serif}main{max-width:1160px;margin:auto;padding:28px}nav{display:flex;gap:22px;flex-wrap:wrap}a{color:#52e0cf}header{margin:28px 0}h1{font-size:clamp(26px,4vw,42px);margin:8px 0}h2{font-size:22px}p{line-height:1.6;color:#bbced1}.badge{display:inline-block;border:1px solid #eab55b;border-radius:20px;padding:6px 12px;color:#f5ce88;font-size:13px}.panel{background:#102e39;border:1px solid #285362;border-radius:16px;padding:22px;margin:18px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px}label{display:block;margin:8px 0}input,select,button{font:inherit;border:1px solid #467483;border-radius:8px;padding:11px;background:#061c24;color:#edf5f5}input,select{width:100%}button{cursor:pointer;background:#13b9a4;color:#041f28;font-weight:700;margin:6px 6px 6px 0}button:disabled{opacity:.5;cursor:not-allowed}button:focus-visible,a:focus-visible{outline:3px solid #ffe075;outline-offset:3px}button.danger{background:#b73143;color:white}code{overflow-wrap:anywhere;font-size:12px}.status{white-space:pre-wrap;border-left:4px solid #eab55b;padding:12px;min-height:44px}small{display:block;color:#acc2c7;line-height:1.5}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}.cards article{border:1px solid #37606c;border-radius:12px;padding:18px}.result{white-space:pre-wrap;overflow-wrap:anywhere}</style></head><body><main>
<nav><a href="/">Gestão WMGJ</a><a href="/downloads">Instaladores</a><a href="#metodo">Modus operandi</a></nav>
<header><span class="badge">AURORA-ORG-001 · Integração 1.1.0-HML</span><h1>Evolução orgânica governada</h1><p>Uma extensão do AURORA NEXUS · JFN-AUD-GOV-001. Mesmo ambiente, mesma organização e mesmo armazenamento.</p></header>
<section id="metodo" class="panel"><h2>Modus operandi</h2><p>Observar → evidenciar → validar → propor → testar → revisar → pilotar → medir → promover ou reverter.</p><p>O piloto deste incremento executa somente contagens de sinais validados. Não altera faturamento, repasses, contratos, fontes ou permissões. Promoção para outras operações permanece sujeita a desenvolvimento e homologação específicos.</p><small>M01–M10 preservados; JFN-AUD-FAT-001/M03.1 permanece como submódulo. Documentos são evidências, nunca comandos. Três referências não comprovam três conteúdos independentes. Benefício informado não é benefício causal ou receita recuperada comprovada.</small></section>
<div id="status" class="status" role="status" aria-live="polite">Verificando sessão e estado...</div>
<section class="panel"><h2>Ocorrência vinculada à operação</h2><small>Somente ação existente e RESOLVED, com autor ainda autorizado e evidências APPROVED / VALIDATED ou CLOSED, não clínicas e não revogadas. Nenhum texto documental é enviado por este formulário.</small>
<form id="observe"><div class="grid"><div><label for="kind">Sinal</label><select id="kind"><option value="REWORK">Retrabalho</option><option value="VALIDATED_DECISION">Decisão validada</option><option value="BILLING_EXCEPTION">Exceção de faturamento</option><option value="SECTOR_NEED">Necessidade setorial</option></select></div><div><label for="category">Categoria</label><select id="category"><option>CONTRACT</option><option>FISCAL</option><option>FINANCIAL</option><option>PRODUCTION</option><option>GOVERNANCE</option><option>AUDIT</option></select></div><div><label for="sector">Setor autorizado</label><select id="sector" required></select></div><div><label for="action">Identificador da ação resolvida</label><input id="action" maxlength="160" pattern="[A-Za-z0-9._:-]+" required autocomplete="off"></div></div><button type="submit">Registrar ocorrência</button></form><button id="revalidate" type="button">Revalidar memória</button><button id="reload" type="button">Atualizar leitura</button></section>
<section class="panel"><h2>Propostas e revisão</h2><small>Aprovação, execução e reversão exigem sessão com segundo fator. Uma mudança de evidência invalida a aprovação anterior. Nenhuma proposta se ativa sozinha.</small><div id="proposals" class="cards"></div></section>
<section class="panel"><h2>Execuções e resultados</h2><small>Classifique somente resultados observados e verificáveis. Repetições sobre os mesmos casos não aumentam o número de observações independentes.</small><div id="runs" class="cards"></div></section>
</main><script nonce="${nonce}">
const csrf=${JSON.stringify(csrf)};let snapshot=null,busy=false,writeEnabled=false;
const el=id=>document.getElementById(id);const message=t=>{el('status').textContent=t;};
function node(tag,text){const n=document.createElement(tag);n.textContent=text;return n;}
function buttons(disabled){document.querySelectorAll('button').forEach(b=>{b.disabled=disabled||(!writeEnabled&&b.id!=='reload');});}
async function load(){const r=await fetch('/organic?format=json',{credentials:'same-origin',cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.code||'READ_FAILED');snapshot=data.state;writeEnabled=data.enabled;el('sector').replaceChildren(...data.sectors.map(s=>{const o=node('option',s);o.value=s;return o;}));render();buttons(false);message(data.enabled?'Estado revalidado: '+snapshot.signalCount+' sinais; '+snapshot.deferredCount+' aguardando revalidação.':'Piloto desativado na organização. A leitura não o habilita.');}
async function send(command){if(busy)return;busy=true;buttons(true);try{const body={...command,expectedVersion:snapshot.version};const key=crypto.randomUUID();const options={method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Aurora-CSRF':csrf,'Idempotency-Key':key},body:JSON.stringify(body)};let r;try{r=await fetch('/organic',options);}catch(_){r=await fetch('/organic',options);}const d=await r.json();if(!r.ok)throw new Error(d.code||'COMMAND_FAILED');await load();message('Registrado: '+command.type+'. Estado '+d.state.version+'.');}catch(e){message('Operação não confirmada: '+e.message+'. Atualize a leitura antes de repetir.');}finally{busy=false;buttons(false);}}
function actionButton(text,command,danger=false){const b=node('button',text);b.type='button';if(danger)b.className='danger';b.addEventListener('click',()=>{if(confirm(text+' nesta revisão?'))send(command);});return b;}
function render(){el('proposals').replaceChildren();for(const p of snapshot.proposals){const card=node('article','');card.append(node('h3',p.template),node('p',p.sector+' · '+p.category+' · revisão '+p.revision),node('p',p.cases+' casos / '+p.evidenceReferences+' referências'),node('p',p.status+' · '+p.approval),node('code',p.id));for(const [type,label] of [['APPROVE_PILOT','Aprovar piloto'],['EXECUTE','Executar contagem'],['ROLLBACK','Reverter piloto']])card.append(actionButton(label,{type,proposalId:p.id,proposalRevision:p.revision},type==='ROLLBACK'));el('proposals').append(card);}if(!snapshot.proposals.length)el('proposals').append(node('p','Nenhuma proposta elegível. São necessários três casos e três referências válidas da mesma categoria e setor.'));el('runs').replaceChildren();for(const r of snapshot.runs){const card=node('article','');card.append(node('h3','Execução · revisão '+r.revision),node('code',r.id),node('p',r.result.cases+' casos; '+r.result.signals+' sinais; sem mutação financeira.'),node('p','Resultado: '+(r.outcome||'a classificar')));if(!r.outcome)for(const [outcome,label] of [['BENEFIT','Benefício observado'],['NO_BENEFIT','Sem benefício'],['ADVERSE','Efeito adverso']])card.append(actionButton(label,{type:'OUTCOME',runId:r.id,outcome},outcome==='ADVERSE'));el('runs').append(card);}}
el('observe').addEventListener('submit',e=>{e.preventDefault();send({type:'OBSERVE',kind:el('kind').value,category:el('category').value,sector:el('sector').value,actionId:el('action').value.trim()});});el('revalidate').onclick=()=>send({type:'REVALIDATE'});el('reload').onclick=()=>load().catch(e=>message(e.message));load().catch(e=>{message('Acesso ou configuração pendente: '+e.message);buttons(true);el('reload').disabled=false;});
</script></body></html>`;
}
