/** Render only after the existing session and membership checks. No new identity store. */
export function setupPage(member: { orgId: string; mfaVerified: boolean }): string {
  const org = member.orgId.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AURORA NEXUS | Instalação e conexões</title><style>
  :root{color-scheme:dark}body{margin:0;background:#071f25;color:#f7f1e7;font:16px system-ui;line-height:1.6}main{max-width:800px;margin:auto;padding:32px 20px}article{background:#0d2d34;border:1px solid #2e5f68;border-radius:14px;padding:20px;margin:16px 0}h1{line-height:1.2}h2{font-size:20px;margin-top:0}a,button{display:inline-block;color:#08191d;background:#c6a45d;border:0;border-radius:8px;padding:10px 16px;font:inherit;text-decoration:none;cursor:pointer}a:focus-visible,button:focus-visible{outline:3px solid white;outline-offset:4px}.pending{color:#f0d99c}small{color:#b9c7c6}button:disabled{opacity:.6}</style></head><body><main>
  <p>AURORA NEXUS · INSTALAÇÃO GUIADA</p><h1>Vamos preparar seu acesso</h1><p>Conclua cada etapa. Este assistente usa a conta e a operação existentes da sua empresa.</p>
  <article><h2>1. Sua conta</h2><p>Sessão e vínculo com a empresa <strong>${org}</strong> verificados.</p><p>${member.mfaVerified ? 'Segundo fator confirmado neste acesso.' : 'Segundo fator não confirmado neste acesso. Entre novamente e selecione a configuração do autenticador.'}</p><small>A sessão pode expirar ou ser revogada. Use seu próprio acesso AURORA; contas administrativas de infraestrutura não são necessárias.</small></article>
  <article><h2>2. Confirmar comunicação</h2><p id="connection" role="status" aria-live="polite">Aguardando verificação do acesso à operação.</p><button id="check" type="button">Verificar agora</button></article>
  <article><h2>3. Conectar as fontes da empresa</h2><p>Abra Integrações no painel para verificar as credenciais AURORA e fontes autorizadas. Uma configuração salva ainda precisa de teste de leitura.</p><p class="pending">Login OAuth de plataformas externas ainda não está disponível neste assistente. Não digite senhas dessas plataformas no instalador.</p><a href="/#integrations">Abrir integrações</a></article>
  <article><h2>4. Conhecer a operação</h2><p>O Motor Mestre analisa as projeções disponíveis e aponta pendências com evidências. A memória operacional é separada por empresa. A instalação não lê automaticamente seus documentos.</p><p>A política da IA Master desabilita chamadas externas. Processamento nativo usa os serviços existentes; JSON é o formato de dados. A continuidade entre nuvem e servidor físico ainda exige verificação conjunta.</p><a href="/#native-intelligence">Abrir Motor Mestre</a></article>
  <article><h2>5. Atualizações e segundo plano</h2><p>Patches do portal usam o atualizador existente. Novos instaladores ficam em Downloads. Esta versão do cliente de acesso ainda não instala execução automática em segundo plano; o componente IA Master do servidor possui seu próprio gerenciador.</p><small>Esta página não comprova instalação no dispositivo, sincronização do servidor físico ou funcionamento sem conexão.</small></article>
  <a href="/">Concluir e abrir a operação</a><script>
  const button=document.getElementById('check'), status=document.getElementById('connection');
  button.addEventListener('click',async()=>{button.disabled=true;status.textContent='Verificando…';try{const response=await fetch('/api/bootstrap',{credentials:'same-origin',cache:'no-store',redirect:'error',signal:AbortSignal.timeout(15000)});if(response.status===401){status.textContent='Sessão expirada. Entre novamente.';return}if(!response.ok||!String(response.headers.get('content-type')).includes('application/json'))throw Error('UNAVAILABLE');status.textContent='Comunicação autenticada confirmada. Isso não comprova ingestão ou sincronização com o servidor físico.'}catch{status.textContent='Comunicação não confirmada. Verifique a conexão e tente novamente.'}finally{button.disabled=false}});
  </script></main></body></html>`;
}
