/** Render only after the existing session and membership checks. No new identity store. */
export function setupPage(member: { orgId: string; mfaVerified: boolean }): string {
  const org = member.orgId.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AURORA NEXUS | Instalação e conexões</title><style>
  :root{color-scheme:dark}body{margin:0;background:#071f25;color:#f7f1e7;font:16px system-ui;line-height:1.6}main{max-width:800px;margin:auto;padding:32px 20px}article{background:#0d2d34;border:1px solid #2e5f68;border-radius:14px;padding:20px;margin:16px 0}h1{line-height:1.2}h2{font-size:20px;margin-top:0}a,button{display:inline-block;color:#08191d;background:#c6a45d;border:0;border-radius:8px;padding:10px 16px;font:inherit;text-decoration:none;cursor:pointer}a:focus-visible,button:focus-visible{outline:3px solid white;outline-offset:4px}.pending{color:#f0d99c}small{color:#b9c7c6}button:disabled{opacity:.6}</style></head><body><main>
  <p>AURORA NEXUS · INSTALAÇÃO GUIADA</p><h1>Vamos preparar seu acesso</h1><p>Conclua cada etapa. Este assistente usa a conta e a operação existentes da sua empresa.</p>
  <article><h2>1. Sua conta</h2><p>Sessão e vínculo com a empresa <strong>${org}</strong> verificados.</p><p>${member.mfaVerified ? 'Segundo fator confirmado neste acesso.' : 'Segundo fator não confirmado neste acesso. Entre novamente e selecione a configuração do autenticador.'}</p><small>A sessão pode expirar ou ser revogada. Use seu próprio acesso AURORA; contas administrativas de infraestrutura não são necessárias.</small></article>
  <article><h2>2. Confirmar comunicação</h2><p id="connection" role="status" aria-live="polite">Aguardando verificação do acesso à operação.</p><button id="check" type="button">Verificar agora</button></article>
  <article><h2>3. Conectar as fontes da empresa</h2><p>Abra Integrações no painel para verificar as credenciais AURORA e fontes autorizadas. Uma configuração salva ainda precisa de teste de leitura.</p><p class="pending">Login OAuth de plataformas externas ainda não está disponível neste assistente. Não digite senhas dessas plataformas no instalador.</p><a href="/#integrations">Abrir integrações</a></article>
  <article><h2>4. Conhecer a operação</h2><p>O Motor Mestre analisa as projeções disponíveis e aponta pendências com evidências. A memória operacional é separada por empresa. A instalação não lê automaticamente seus documentos.</p><p>A política da IA Master desabilita chamadas externas. Processamento nativo usa os serviços existentes; JSON é o formato de dados. A continuidade entre nuvem e servidor físico ainda exige verificação conjunta.</p><a href="/#native-intelligence">Abrir Motor Mestre</a></article>
  <article><h2>5. Atualizações e segundo plano</h2><p>Patches do portal usam o atualizador existente. Novos instaladores ficam em Downloads. Esta versão do cliente de acesso ainda não instala execução automática em segundo plano; o componente IA Master do servidor possui seu próprio gerenciador.</p><small>Esta página não comprova instalação no dispositivo, sincronização do servidor físico ou funcionamento sem conexão.</small></article>
  <article><h2>6. Primeiros dados da empresa</h2><p id="ingestion" role="status" aria-live="polite">Verificando a primeira ingestão…</p><small>O cadastro preserva seu acesso. A preparação operacional só conclui após dados autorizados persistidos e processados pela operação da sua empresa. Sem fonte configurada, abra Integrações.</small></article>
  <button id="complete" type="button" disabled>Concluir e abrir a operação</button><script>
  const button=document.getElementById('check'), status=document.getElementById('connection');
  const complete=document.getElementById('complete'), ingestion=document.getElementById('ingestion');
  const expectedOrg=${JSON.stringify(member.orgId).replace(/</g,'\\u003c')};
  const messages={PENDING_SOURCE:'Fonte autorizada ainda sem primeiro recibo. Abra Integrações para conectar sua fonte.',PENDING_CANONICAL_DATA:'Dados recebidos; aguardando validação dos campos e da fonte.',PENDING_PROJECTION:'Dados persistidos; aguardando processamento da operação.'};
  let attempts=0,timer=null,checking=false;
  async function check(){if(checking)return;checking=true;clearTimeout(timer);complete.disabled=true;button.disabled=true;status.textContent='Verificando…';try{const response=await fetch('/api/bootstrap',{credentials:'same-origin',cache:'no-store',redirect:'error',signal:AbortSignal.timeout(15000)});if(response.status===401){status.textContent='Sessão expirada. Entre novamente.';ingestion.textContent='Preparação pendente de autenticação.';return}if(!response.ok||!String(response.headers.get('content-type')).includes('application/json'))throw Error('UNAVAILABLE');const data=await response.json();if(data.ok!==true||data.organization?.id!==expectedOrg)throw Error('SCOPE_MISMATCH');status.textContent='Comunicação autenticada confirmada. Isso não comprova ingestão ou sincronização com o servidor físico.';const proof=data.installation;const ready=proof?.state==='FIRST_INGESTION_VERIFIED'&&proof.firstIngestionVerified===true&&/^[a-f0-9]{48}$/.test(proof.documentId||'')&&Number.isSafeInteger(proof.sourceVersion)&&proof.sourceVersion>0&&Number.isFinite(Date.parse(proof.verifiedAt));complete.disabled=!ready;ingestion.textContent=ready?'Primeira ingestão e processamento confirmados para sua empresa.':messages[proof?.state]||'Aguardando evidência atual da primeira ingestão.';if(!ready&&++attempts<12)timer=setTimeout(check,5000)}catch{status.textContent='Comunicação não confirmada. Verifique a conexão e tente novamente.';ingestion.textContent='Preparação pendente. Seu cadastro foi preservado.';if(++attempts<12)timer=setTimeout(check,5000)}finally{button.disabled=false;checking=false}}
  button.addEventListener('click',()=>{attempts=0;check()});
  complete.addEventListener('click',()=>{if(!complete.disabled)window.location.assign('/portal')});
  check();
  </script></main></body></html>`;
}
