import test from 'node:test';
import assert from 'node:assert/strict';
import {Script,createContext} from 'node:vm';
import {setImmediate} from 'node:timers/promises';
import {organicPage} from '../src/auroraOrganicView.js';
type Handler=(event?:any)=>unknown;
class Element {
 id:string;constructor(id=''){this.id=id;}
 textContent='';value='';hidden=false;disabled=false;className='';type='';dataset:Record<string,string>={};children:Element[]=[];handlers=new Map<string,Handler>();onclick:Handler|null=null;parentForm:Element|null=null;
 append(...es:Element[]){this.children.push(...es);}replaceChildren(...es:Element[]){this.children=[...es];this.textContent='';}
 addEventListener(name:string,fn:Handler){this.handlers.set(name,fn);}reset(){this.value='';}closest(_selector:string){return this.parentForm;}
}
const html=organicPage('v1.synthetic.signature','nonce');
const script=html.match(/<script nonce="nonce">([\s\S]*?)<\/script>/)![1]!;
const data={ok:true,enabled:true,sectors:['AUDIT'],state:{version:3,signalCount:3,deferredCount:0,proposals:[],runs:[],learning:{tools:[]}}};
const response=(status=200,body:any=data)=>({status,ok:status>=200&&status<300,json:async()=>body});
async function fixture(){
 const elements=new Map([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>[m[1]!,new Element(m[1])]));
 const dynamic:Element[]=[];const docHandlers=new Map<string,Handler>();const winHandlers=new Map<string,Handler>();
 const document={visibilityState:'visible',activeElement:null as Element|null,getElementById(id:string){const e=elements.get(id);assert.ok(e,id);return e;},createElement(tag:string){const e=new Element(tag);dynamic.push(e);return e;},querySelectorAll(_s:string){return [...['reload','retry','revalidate'].map(id=>elements.get(id)!),...dynamic.filter(e=>e.id==='button')];},addEventListener(n:string,f:Handler){docHandlers.set(n,f);}};
 const calls:{url:string;options:any}[]=[],redirects:string[]=[],intervals:{fn:Handler;ms:number}[]=[],timers=new Map<number,Handler>();let timer=0,uuid=0;
 let fetcher=async(_url:string,_options:any):Promise<any>=>response();
 const context=createContext({document,window:{addEventListener:(n:string,f:Handler)=>winHandlers.set(n,f)},navigator:{onLine:true},location:{replace:(url:string)=>redirects.push(url)},crypto:{randomUUID:()=>`synthetic-key-${++uuid}`},AbortController,confirm:()=>true,setTimeout:(fn:Handler)=>{const id=++timer;timers.set(id,fn);return id;},clearTimeout:(id:number)=>timers.delete(id),setInterval:(fn:Handler,ms:number)=>intervals.push({fn,ms}),fetch:(url:string,options:any)=>{calls.push({url,options});return fetcher(url,options);}});
 new Script(script).runInContext(context);await setImmediate();
 return {elements,document,calls,redirects,intervals,timers,docHandlers,winHandlers,context,fetchWith(fn:typeof fetcher){fetcher=fn;},run(code:string){return new Script(code).runInContext(context);}};
}
test('emitted script parses and initializes private snapshot',async()=>{assert.doesNotThrow(()=>new Script(script));const f=await fixture();assert.equal(f.elements.get('work')!.hidden,false);assert.equal(f.calls[0]!.options.cache,'no-store');});
test('only read polling occurs automatically every 60 seconds',async()=>{const f=await fixture();assert.equal(f.intervals.length,1);assert.equal(f.intervals[0]!.ms,60000);await f.intervals[0]!.fn();assert.equal(f.calls.length,2);assert.ok(f.calls.every(c=>c.url.includes('format=json')&&!c.options.method));});
test('polling pauses hidden, offline and during editing',async()=>{const f=await fixture();f.document.visibilityState='hidden';await f.intervals[0]!.fn();f.document.visibilityState='visible';f.run('navigator.onLine=false');await f.intervals[0]!.fn();f.run('navigator.onLine=true');const e=new Element();e.parentForm=new Element();f.document.activeElement=e;await f.intervals[0]!.fn();assert.equal(f.calls.length,1);});
test('500 keeps the exact command/key; retry does not create a new operation',async()=>{const f=await fixture();f.fetchWith(async()=>response(500,{ok:false,code:'ORGANIC_FAILED'}));await f.run("send({type:'REVALIDATE'})");const first=f.calls[1]!;assert.equal(f.elements.get('retry')!.hidden,false);assert.equal(f.elements.get('work')!.hidden,true);f.fetchWith(async()=>response());await f.run('transmitPending()');const second=f.calls[2]!;assert.equal(first.options.body,second.options.body);assert.equal(first.options.headers['Idempotency-Key'],second.options.headers['Idempotency-Key']);assert.equal(f.run('pending'),null);});
test('no new command or automatic polling while a write remains unconfirmed',async()=>{const f=await fixture();f.fetchWith(async()=>{throw new Error('network');});await f.run("send({type:'REVALIDATE'})");const count=f.calls.length;await f.run("send({type:'OBSERVE'})");await f.intervals[0]!.fn();assert.equal(f.calls.length,count);});
test('a later read cannot declare an unknown write successful',async()=>{const f=await fixture();f.fetchWith(async()=>response(500));await f.run("send({type:'REVALIDATE'})");f.fetchWith(async()=>response(200,{...data,state:{...data.state,version:99}}));await f.run('load()');assert.notEqual(f.run('pending'),null);assert.match(f.elements.get('status')!.textContent,/sem confirmação/);});
for(const status of [401,403])test('authorization '+status+' clears view and halts retries',async()=>{const f=await fixture();f.fetchWith(async()=>response(status,{ok:false,code:'AUTH_REQUIRED'}));await f.run('load()');assert.equal(f.elements.get('work')!.hidden,true);assert.equal(f.run('snapshot'),null);const count=f.calls.length;await f.run("send({type:'REVALIDATE'})");await f.intervals[0]!.fn();assert.equal(f.calls.length,count);assert.equal(f.redirects.length,status===401?1:0);});
test('409 rejects stale command and requires a fresh read',async()=>{const f=await fixture();f.fetchWith(async()=>response(409,{ok:false,code:'REVISION_CONFLICT'}));await f.run("send({type:'REVALIDATE'})");assert.equal(f.run('pending'),null);assert.equal(f.run('snapshot'),null);assert.match(f.elements.get('status')!.textContent,/REVISION_CONFLICT/);});
test('timeout aborts a write but preserves its idempotency key for explicit retry',async()=>{const f=await fixture();f.fetchWith(async(_url,opt)=>new Promise((_resolve,reject)=>opt.signal.addEventListener('abort',()=>reject(new Error('timeout')))));const p=f.run("send({type:'REVALIDATE'})");assert.equal(f.timers.size,1);[...f.timers.values()][0]!();await p;assert.notEqual(f.run('pending'),null);assert.equal(f.timers.size,0);});
test('successful write with failed subsequent read is still distinguished',async()=>{const f=await fixture();f.fetchWith(async(_url,opt)=>opt.method==='POST'?response():response(500));await f.run("send({type:'REVALIDATE'})");assert.equal(f.run('pending'),null);assert.match(f.elements.get('status')!.textContent,/Registro confirmado/);assert.match(f.elements.get('status')!.textContent,/leitura posterior não foi confirmada/);assert.equal(f.elements.get('work')!.hidden,true);});
test('disabled pilot allows rollback, not new activation',async()=>{const f=await fixture();f.fetchWith(async()=>response(200,{...data,enabled:false}));await f.run('load()');const count=f.calls.length;await f.run("send({type:'REVALIDATE'})");assert.equal(f.calls.length,count);await f.run("send({type:'ROLLBACK',proposalId:'synthetic',proposalRevision:1})");assert.equal(f.calls.filter(c=>c.options.method==='POST').length,1);});
test('HTML error response is not exposed or treated as confirmed',async()=>{const f=await fixture();f.fetchWith(async()=>({status:500,ok:false,json:async()=>{throw new Error('<secret>');}}));await f.run("send({type:'REVALIDATE'})");assert.ok(!f.elements.get('status')!.textContent.includes('<secret>'));assert.notEqual(f.run('pending'),null);});
